import { database } from '../database';
import AccountModel from './Account.model';
import EntityPhotoModel from './entityPhoto.model';
import InvitationModel from './invitation.model';
import LocationModel from './location.model';
import PhotoModel from './photo.model';
import ProductModel from './product.model';
import ProductCollectionModel from './ProductCollection.model';
import ProductInCollectionModel from './ProductInCollection.model';
import TaggedModel from './tagged.model';
import VendorModel from './vendor.model';
import VendorLocationModel from './vendorLocation.model';

export * from './types';
export const vendorModel = new VendorModel(database);
export const locationModel = new LocationModel(database);
export const vendorLocationModel = new VendorLocationModel(database);
export const taggedModel = new TaggedModel(database);
export const photoModel = new PhotoModel(database);
export const entityPhotoModel = new EntityPhotoModel(database);
export const productModel = new ProductModel(database);
export const productCollectionModel = new ProductCollectionModel(database);
export const productInCollectionModel = new ProductInCollectionModel(database);
export const invitationModel = new InvitationModel(database);
export const accountModel = new AccountModel(database);